apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-support-app
  labels:
    app: customer-support-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-support-app
  template:
    metadata:
      labels:
        app: customer-support-app
    spec:
      containers:
        - name: customer-support-app
          image: localhost:5000/cs-app:0.0.4
          imagePullPolicy: IfNotPresent
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: customer-support-api
                  key: OPENAI_API_KEY
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
       
