apiVersion: v1
kind: Secret
metadata:
  name: customer-support-api
type: Opaque
stringData:
  OPENAI_API_KEY: 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
